### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by lucav17** [joshparkAS/project-3-the-scoop#2]
I noticed you passed all cases besides 4. I would look into those and check what input was throwing errors. In some cases you received an undefined. I would work with it till all test cases are passed!

**Comment by joshparkAS** [comment]
Okay I realized I made a simple error and changed one of my responses from 200 to 400. So I ran the tests again and I realized I'm still failing 2 cases. They're both similar and regarding the upvote/downvote Comment function.

  1) Scoop - server.js:  /commnets/:id/upvote PUT routes['/comments/:id/upvote'].PUT should return a 400 response when given no request body:
     TypeError: Cannot read property 'username' of undefined
      at Object.upvoteComment [as PUT] (server.js:167:33)
      at Context.<anonymous> (test/test.js:464:61)

I put in a condition, however, that database.users[username] needs to exist but it doesn't seem to pass the case? Do you know what I'm doing wrong?
